[package]
name = "raft-client"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tonic = "0.12"
ratatui = "0.29"
crossterm = "0.29"
rand = "0.8"

# Local
raft-proto = { path = "../raft-proto" }
